[template]
cargo_generate_version = ">=0.18"

# 不对这些文件做 {{ }} 替换
exclude = [
  ".pre-commit-config.yaml",
  "cliff.toml",
  "CHANGELOG.md",
]

[placeholders.company]
type = "string"
prompt = "Company name"
default = "your-company"

[placeholders.service]
type = "string"
prompt = "Service logical name"
default = "service"

[placeholders.description]
type = "string"
prompt = "Project description"
default = "Enterprise Rust service"
