[package]
name = "{{ project-name | kebab_case }}"
version = "0.1.0"
edition = "2024"
authors = ["{{ authors }}"]
description = "{{ description }}"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
